import { useEffect, useMemo, useState } from 'react'
import { ArrowLeft, CreditCard, RotateCcw, ShieldCheck } from 'lucide-react'
import { authApi, getMerchantContexts, type MerchantContext, type OrderRow } from './lib/posApi'
import { getRefundableOrders, getRefunds, getSubscription, type RefundRow, type Subscription } from './lib/advancedOpsApi'
import { createBillingCheckout, partialRefundOrder, submitBillingPayment, type BillingCheckout } from './lib/remainingOpsApi'

const money=(n:number)=>new Intl.NumberFormat('en-PH',{style:'currency',currency:'PHP',maximumFractionDigits:2}).format(Number(n)||0)

type Tab='billing'|'refunds'

export default function LaunchCenter(){
 const[context,setContext]=useState<MerchantContext|null>(null),[subscription,setSubscription]=useState<Subscription|null>(null),[orders,setOrders]=useState<OrderRow[]>([]),[refunds,setRefunds]=useState<RefundRow[]>([])
 const[tab,setTab]=useState<Tab>('billing'),[error,setError]=useState(''),[notice,setNotice]=useState(''),[loading,setLoading]=useState(true)
 const refresh=async(ctx:MerchantContext)=>{const[s,o,r]=await Promise.all([getSubscription(ctx.merchant_id),getRefundableOrders(ctx.merchant_id),getRefunds(ctx.merchant_id)]);setSubscription(s);setOrders(o);setRefunds(r)}
 useEffect(()=>{void(async()=>{try{const s=await authApi.session();if(!s)throw new Error('Sign in from the POS first.');const c=await getMerchantContexts();if(!c.length)throw new Error('No approved merchant account found.');setContext(c[0]);await refresh(c[0])}catch(e){setError(msg(e))}finally{setLoading(false)}})()},[])
 if(loading)return <Frame><p>Loading launch center…</p></Frame>
 if(!context)return <Frame><div className="inline-error">{error||'Merchant account unavailable.'}</div></Frame>
 return <Frame><header className="ops-head"><button className="secondary small" onClick={()=>history.back()}><ArrowLeft/> POS</button><div><p className="eyebrow">Launch center</p><h1>{context.merchant_name}</h1></div></header>{error&&<div className="inline-error">{error}<button onClick={()=>setError('')}>×</button></div>}{notice&&<div className="inline-notice">{notice}<button onClick={()=>setNotice('')}>×</button></div>}<nav className="ops-tabs"><button className={tab==='billing'?'active':''} onClick={()=>setTab('billing')}>billing</button><button className={tab==='refunds'?'active':''} onClick={()=>setTab('refunds')}>refunds</button></nav>{tab==='billing'?<Billing context={context} subscription={subscription} onNotice={setNotice} onError={setError}/>:<Refunds orders={orders} refunds={refunds} onDone={()=>refresh(context)} onNotice={setNotice} onError={setError}/>}</Frame>
}

function Frame({children}:{children:React.ReactNode}){return <div className="app-shell"><main className="content ops-workspace">{children}</main></div>}

function Billing({context,subscription,onNotice,onError}:{context:MerchantContext;subscription:Subscription|null;onNotice:(s:string)=>void;onError:(s:string)=>void}){
 const[checkout,setCheckout]=useState<BillingCheckout|null>(null),[method,setMethod]=useState(''),[reference,setReference]=useState(''),[busy,setBusy]=useState(false)
 const label=context.plan_code==='community_free'?'Free':context.plan_code==='pro'?'Pro':'Business+'
 const start=async(plan:'pro'|'business_plus',period:'monthly'|'annual')=>{setBusy(true);try{const c=await createBillingCheckout(context.merchant_id,plan,period);setCheckout(c);setMethod('');setReference('');onNotice(`Upgrade request created for ${money(c.amount)}.`)}catch(e){onError(msg(e))}finally{setBusy(false)}}
 const submit=async()=>{if(!checkout||!method.trim()||!reference.trim())return;setBusy(true);try{await submitBillingPayment(checkout.checkout_id,method.trim(),reference.trim());setCheckout({...checkout,status:'submitted'});onNotice('Payment reference submitted for verification. Your current plan stays active until verification is completed.')}catch(e){onError(msg(e))}finally{setBusy(false)}}
 return <section><h2>Plan & billing</h2><div className="plan-card"><strong>{label}</strong><span>Status: {subscription?.status||'active'} · {subscription?.billing_period||'manual'} billing</span></div><div className="guardrail-note"><ShieldCheck/><p>Launch billing is verification-based. Creating or submitting a payment request never unlocks paid features by itself. Plan activation remains server-controlled after payment is verified.</p></div>{context.role==='owner'&&<div className="stack-form"><button className="primary" disabled={busy} onClick={()=>void start('pro','monthly')}>Pro · ₱249/month</button><button className="secondary" disabled={busy} onClick={()=>void start('pro','annual')}>Pro · ₱1,990/year</button><button className="secondary" disabled={busy} onClick={()=>void start('business_plus','monthly')}>Business+ · ₱399/month</button><button className="secondary" disabled={busy} onClick={()=>void start('business_plus','annual')}>Business+ · ₱2,990/year</button></div>}{checkout&&<div className="stack-form"><div className="guardrail-note"><CreditCard/><p>Request #{checkout.checkout_id.slice(0,8)} · {money(checkout.amount)} · {checkout.status}. Pay using the payment channel provided by the POS administrator, then submit the exact reference below.</p></div><label>Payment method<input value={method} disabled={checkout.status==='submitted'} onChange={e=>setMethod(e.target.value)} placeholder="Example: GCash, Maya, bank transfer"/></label><label>Payment reference<input value={reference} disabled={checkout.status==='submitted'} onChange={e=>setReference(e.target.value)} placeholder="Transaction/reference number"/></label><button className="primary" disabled={busy||checkout.status==='submitted'||!method.trim()||!reference.trim()} onClick={()=>void submit()}>{checkout.status==='submitted'?'Submitted for verification':'Submit payment reference'}</button></div>}</section>
}

function Refunds({orders,refunds,onDone,onNotice,onError}:{orders:OrderRow[];refunds:RefundRow[];onDone:()=>Promise<void>;onNotice:(s:string)=>void;onError:(s:string)=>void}){
 const[selected,setSelected]=useState<OrderRow|null>(null),[amount,setAmount]=useState(''),[reason,setReason]=useState(''),[restock,setRestock]=useState<Record<string,number>>({}),[busy,setBusy]=useState(false)
 const refundedByOrder=useMemo(()=>refunds.reduce<Record<string,number>>((a,r)=>{a[r.order_id]=(a[r.order_id]||0)+Number(r.amount);return a},{}),[refunds])
 const choose=(o:OrderRow)=>{setSelected(o);setAmount(String(Math.max(0,Number(o.total)-(refundedByOrder[o.id]||0))));setReason('');setRestock({})}
 const submit=async()=>{if(!selected)return;const value=Number(amount);if(!value||value<=0||!reason.trim())return;setBusy(true);try{const result=await partialRefundOrder({orderId:selected.id,amount:value,reason:reason.trim(),restockItems:Object.entries(restock).filter(([,q])=>q>0).map(([order_item_id,quantity])=>({order_item_id,quantity}))});onNotice(result.fully_refunded?`Order #${selected.order_number} fully refunded.`:`Partial refund recorded. ${money(result.remaining)} remains refundable.`);setSelected(null);await onDone()}catch(e){onError(msg(e))}finally{setBusy(false)}}
 return <section><h2>Refunds & returns</h2><div className="guardrail-note"><RotateCcw/><p>Owners and managers can issue full or partial refunds. Optional item quantities can be returned to branch stock. Every refund is recorded in the audit trail.</p></div><div className="settings-list">{orders.map(o=>{const refunded=refundedByOrder[o.id]||0;const remaining=Math.max(0,Number(o.total)-refunded);return <div className="marketplace-product-row" key={o.id}><div className="settings-copy"><strong>#{o.order_number} · {o.customer_name}</strong><small>{money(remaining)} refundable · {money(refunded)} already refunded · {o.source}</small></div><button className="secondary small" disabled={remaining<=0} onClick={()=>choose(o)}>Refund</button></div>})}</div>{selected&&<div className="stack-form"><h3>Refund order #{selected.order_number}</h3><label>Refund amount<input type="number" min="0.01" step="0.01" max={Math.max(0,Number(selected.total)-(refundedByOrder[selected.id]||0))} value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>Reason<textarea required value={reason} onChange={e=>setReason(e.target.value)} placeholder="Reason for refund"/></label><div className="settings-list">{selected.pos_order_items.map(item=><label className="marketplace-product-row" key={item.id}><span className="settings-copy"><strong>{item.product_name}</strong><small>Sold quantity: {item.quantity}</small></span><span>Restock <input type="number" min="0" max={item.quantity} step="1" value={restock[item.id]||0} onChange={e=>setRestock(v=>({...v,[item.id]:Number(e.target.value)}))}/></span></label>)}</div><button className="primary" disabled={busy||!Number(amount)||!reason.trim()} onClick={()=>void submit()}>{busy?'Saving…':'Record refund'}</button><button className="secondary" disabled={busy} onClick={()=>setSelected(null)}>Cancel</button></div>}</section>
}

function msg(e:unknown){return e instanceof Error?e.message:String(e||'Something went wrong')}
