import { FormEvent, useEffect, useMemo, useState } from 'react'
import { ArrowLeft, Building2, CreditCard, FileBarChart2, PackagePlus, RotateCcw, Store, Truck } from 'lucide-react'
import { authApi, getMerchantContexts, type MerchantContext, type OrderRow } from './lib/posApi'
import {
  createPurchaseOrder, createSupplier, getFeatures, getInventoryInsights, getOutletFulfillment,
  getPurchaseOrders, getRefundableOrders, getRefunds, getReport, getSubscription, getSuppliers,
  refundOrder, updateOutletFulfillment,
  type InventoryInsight, type OutletFulfillment, type PlanFeature, type PurchaseOrder,
  type ReportSummary, type Subscription, type Supplier,
} from './lib/advancedOpsApi'

const money=(n:number)=>new Intl.NumberFormat('en-PH',{style:'currency',currency:'PHP',maximumFractionDigits:0}).format(Number(n)||0)
type Section='overview'|'marketplace'|'branches'|'inventory'|'suppliers'|'reports'|'refunds'|'billing'

export default function OperationsHub(){
 const [context,setContext]=useState<MerchantContext|null>(null),[contexts,setContexts]=useState<MerchantContext[]>([])
 const [section,setSection]=useState<Section>('overview'),[features,setFeatures]=useState<PlanFeature[]>([]),[subscription,setSubscription]=useState<Subscription|null>(null)
 const [suppliers,setSuppliers]=useState<Supplier[]>([]),[purchaseOrders,setPurchaseOrders]=useState<PurchaseOrder[]>([]),[report,setReport]=useState<ReportSummary|null>(null)
 const [insights,setInsights]=useState<InventoryInsight[]>([]),[fulfillment,setFulfillment]=useState<OutletFulfillment|null>(null),[orders,setOrders]=useState<OrderRow[]>([]),[refunds,setRefunds]=useState<any[]>([])
 const [error,setError]=useState(''),[loading,setLoading]=useState(true)
 const enabled=(code:string)=>features.some(f=>f.feature_code===code&&f.enabled)
 useEffect(()=>{void(async()=>{try{const s=await authApi.session();if(!s)throw new Error('Sign in from the POS first.');const all=await getMerchantContexts();if(!all.length)throw new Error('No approved merchant account found.');setContexts(all);setContext(all[0])}catch(e){setError(msg(e))}finally{setLoading(false)}})()},[])
 useEffect(()=>{const ctx=context;const outletId=ctx?.outlet_id;if(!ctx||!outletId)return;void(async()=>{try{const [f,s,sup,po,r,o,rf,i,ff]=await Promise.all([getFeatures(ctx.plan_code),getSubscription(ctx.merchant_id),getSuppliers(ctx.merchant_id).catch(()=>[]),getPurchaseOrders(ctx.merchant_id).catch(()=>[]),getReport(ctx.merchant_id,outletId),getRefundableOrders(ctx.merchant_id),getRefunds(ctx.merchant_id),getInventoryInsights(ctx.merchant_id),getOutletFulfillment(outletId)]);setFeatures(f);setSubscription(s);setSuppliers(sup);setPurchaseOrders(po);setReport(r);setOrders(o);setRefunds(rf);setInsights(i);setFulfillment(ff)}catch(e){setError(msg(e))}})()},[context?.merchant_id,context?.outlet_id])
 const branchRows=useMemo(()=>contexts.filter(c=>c.merchant_id===context?.merchant_id),[contexts,context?.merchant_id])
 const refreshAfterRefund=async()=>{if(!context)return;const[o,rf,r,i]=await Promise.all([getRefundableOrders(context.merchant_id),getRefunds(context.merchant_id),getReport(context.merchant_id,context.outlet_id),getInventoryInsights(context.merchant_id)]);setOrders(o);setRefunds(rf);setReport(r);setInsights(i)}
 if(loading)return <Frame><p>Loading operations…</p></Frame>
 if(error&&!context)return <Frame><div className="inline-error">{error}</div></Frame>
 return <Frame>
  <header className="ops-head"><button className="secondary small" onClick={()=>history.back()}><ArrowLeft/> POS</button><div><p className="eyebrow">{context?.merchant_name}</p><h1>Business Operations</h1></div></header>
  {error&&<div className="inline-error">{error}<button onClick={()=>setError('')}>×</button></div>}
  {context&&branchRows.length>1&&<label className="ops-branch-select">Working location<select value={context.outlet_id||''} onChange={e=>{const next=branchRows.find(c=>c.outlet_id===e.target.value);if(next)setContext(next)}}>{branchRows.map(c=><option key={c.outlet_id||'none'} value={c.outlet_id||''}>{c.outlet_name||'Main'}</option>)}</select></label>}
  <nav className="ops-tabs">{(['overview','marketplace','branches','inventory','suppliers','reports','refunds','billing'] as Section[]).map(x=><button className={section===x?'active':''} onClick={()=>setSection(x)} key={x}>{x}</button>)}</nav>
  {section==='overview'&&<Overview report={report} context={context} enabled={enabled}/>} 
  {section==='marketplace'&&<MarketplaceFulfillment data={fulfillment} save={async next=>{const outletId=context?.outlet_id;if(!outletId)return;await updateOutletFulfillment({outletId,pickupEnabled:next.pickup_enabled,deliveryEnabled:next.delivery_enabled,deliveryFee:next.delivery_fee,minimumOrder:next.minimum_delivery_order});setFulfillment(await getOutletFulfillment(outletId))}}/>}
  {section==='branches'&&<Branches rows={branchRows} enabled={enabled('multi_branch')}/>} 
  {section==='inventory'&&<Inventory rows={insights}/>} 
  {section==='suppliers'&&<Suppliers context={context} enabled={enabled('suppliers')} suppliers={suppliers} setSuppliers={setSuppliers} purchaseOrders={purchaseOrders} setPurchaseOrders={setPurchaseOrders} onError={setError}/>} 
  {section==='reports'&&<Reports report={report} advanced={enabled('advanced_reports')}/>} 
  {section==='refunds'&&<Refunds orders={orders} refunds={refunds} enabled={enabled('refunds')} onDone={refreshAfterRefund} onError={setError}/>} 
  {section==='billing'&&<Billing context={context} subscription={subscription} features={features}/>} 
 </Frame>
}

function Frame({children}:{children:React.ReactNode}){return <div className="app-shell"><main className="content ops-workspace">{children}</main></div>}
function Overview({report,context,enabled}:{report:ReportSummary|null;context:MerchantContext|null;enabled:(x:string)=>boolean}){return <section><div className="metric-strip"><Metric l="Net sales" v={money(report?.net_sales||0)}/><Metric l="Orders" v={String(report?.orders||0)}/><Metric l="Expenses" v={money(report?.expenses||0)}/></div><div className="settings-list"><Card icon={<Building2/>} title="Current branch" desc={context?.outlet_name||'Main'}/><Card icon={<Store/>} title="Marketplace" desc={enabled('marketplace_selling')?'Included':'Not enabled'}/><Card icon={<FileBarChart2/>} title="Advanced reports" desc={enabled('advanced_reports')?'Enabled':'Upgrade to Pro'}/></div></section>}
function MarketplaceFulfillment({data,save}:{data:OutletFulfillment|null;save:(v:OutletFulfillment)=>Promise<void>}){const[d,setD]=useState(data);useEffect(()=>setD(data),[data]);if(!d)return <p>Loading fulfillment settings…</p>;const persist=async(p:Partial<OutletFulfillment>)=>{const n={...d,...p};setD(n);await save(n)};return <section><h2>Marketplace fulfillment</h2><div className="guardrail-note"><Store/><p>Marketplace uses the same pickup and delivery rules as POS. No duplicate fulfillment database.</p></div><div className="stack-form"><label className="loyalty-check"><input type="checkbox" checked={d.pickup_enabled} onChange={e=>void persist({pickup_enabled:e.target.checked})}/><span>Allow pickup</span></label><label className="loyalty-check"><input type="checkbox" checked={d.delivery_enabled} onChange={e=>void persist({delivery_enabled:e.target.checked})}/><span>Allow store delivery</span></label><label>Delivery fee<input type="number" min="0" value={d.delivery_fee} onChange={e=>setD({...d,delivery_fee:Number(e.target.value)})} onBlur={()=>void save(d)}/></label><label>Minimum delivery order<input type="number" min="0" value={d.minimum_delivery_order} onChange={e=>setD({...d,minimum_delivery_order:Number(e.target.value)})} onBlur={()=>void save(d)}/></label></div></section>}
function Branches({rows,enabled}:{rows:MerchantContext[];enabled:boolean}){return <section><h2>Locations</h2><div className="guardrail-note"><Building2/><p>{enabled?'Business+ can operate multiple locations. Use the location selector above for branch-specific operations.':'Your current plan supports one location. Multi-branch is a Business+ capability.'}</p></div><div className="settings-list">{rows.map(r=><Card key={r.outlet_id||r.merchant_id} icon={<Store/>} title={r.outlet_name||'Main'} desc="Active outlet"/>)}</div></section>}
function Inventory({rows}:{rows:InventoryInsight[]}){return <section><h2>Inventory insights</h2><div className="settings-list">{rows.map(r=><div className="marketplace-product-row" key={r.product_id}><div className="settings-copy"><strong>{r.name}</strong><small>{r.stock_on_hand} stock · {money(r.inventory_value)} value · {r.average_daily_usage}/day{r.days_remaining===null?'':` · ${r.days_remaining} days left`}</small></div>{r.low_stock&&<span className="status status-payment_review">Low</span>}</div>)}</div>{!rows.length&&<p className="body-copy">Track inventory and product cost to unlock valuation and usage forecasting.</p>}</section>}
function Suppliers({context,enabled,suppliers,setSuppliers,purchaseOrders,setPurchaseOrders,onError}:any){const[name,setName]=useState(''),[supplierId,setSupplierId]=useState(''),[ref,setRef]=useState('');const add=async(e:FormEvent)=>{e.preventDefault();try{await createSupplier(context.merchant_id,{name});setName('');setSuppliers(await getSuppliers(context.merchant_id))}catch(x){onError(msg(x))}};const po=async(e:FormEvent)=>{e.preventDefault();try{const next=await createPurchaseOrder({merchantId:context.merchant_id,outletId:context.outlet_id,supplierId:supplierId||undefined,reference:ref||undefined});setPurchaseOrders([next,...purchaseOrders]);setRef('')}catch(x){onError(msg(x))}};if(!enabled)return <Upgrade title="Suppliers & purchasing"/>;return <section><h2>Suppliers & purchasing</h2><form className="stack-form" onSubmit={add}><label>Supplier name<input required value={name} onChange={e=>setName(e.target.value)}/></label><button className="primary">Add supplier</button></form><form className="stack-form" onSubmit={po}><label>Supplier<select value={supplierId} onChange={e=>setSupplierId(e.target.value)}><option value="">No supplier</option>{suppliers.map((s:Supplier)=><option value={s.id} key={s.id}>{s.name}</option>)}</select></label><label>PO reference<input value={ref} onChange={e=>setRef(e.target.value)}/></label><button className="primary">Create purchase order</button></form><div className="settings-list">{purchaseOrders.map((p:PurchaseOrder)=><Card key={p.id} icon={<Truck/>} title={p.reference||'Purchase order'} desc={p.status}/>)}</div></section>}
function Reports({report,advanced}:{report:ReportSummary|null;advanced:boolean}){if(!report)return <p>No report data.</p>;const profit=report.net_sales-report.cogs-report.expenses;return <section><h2>Reports</h2><div className="metric-strip"><Metric l="Gross sales" v={money(report.gross_sales)}/><Metric l="Refunds" v={money(report.refunds)}/><Metric l="Net sales" v={money(report.net_sales)}/></div><div className="metric-strip"><Metric l="COGS" v={money(report.cogs)}/><Metric l="Expenses" v={money(report.expenses)}/><Metric l="Est. operating profit" v={money(profit)}/></div>{advanced?<div className="settings-list"><Card icon={<Store/>} title="POS sales" desc={money(report.pos_sales)}/><Card icon={<Store/>} title="Marketplace sales" desc={money(report.marketplace_sales)}/><Card icon={<Store/>} title="QR sales" desc={money(report.qr_sales)}/><Card icon={<PackagePlus/>} title="Inventory value" desc={money(report.inventory_value)}/></div>:<Upgrade title="Source and inventory reporting"/>}</section>}
function Refunds({orders,refunds,enabled,onDone,onError}:any){if(!enabled)return <Upgrade title="Refunds"/>;const act=async(o:OrderRow)=>{const reason=prompt(`Refund order #${o.order_number}. Reason:`)?.trim();if(!reason)return;const restock=confirm('Return tracked items to inventory?');try{await refundOrder(o.id,reason,restock);await onDone()}catch(e){onError(msg(e))}};return <section><h2>Refunds & returns</h2><div className="guardrail-note"><RotateCcw/><p>Full-refund MVP. Owner or manager approval is required. Optional restock writes an auditable inventory return.</p></div><div className="settings-list">{orders.map((o:OrderRow)=><div className="marketplace-product-row" key={o.id}><div className="settings-copy"><strong>#{o.order_number} · {o.customer_name}</strong><small>{money(o.total)} · {o.source}</small></div><button className="secondary small" onClick={()=>void act(o)}>Refund</button></div>)}</div>{refunds.length>0&&<p className="tool-footnote">{refunds.length} recorded refund{refunds.length===1?'':'s'}.</p>}</section>}
function Billing({context,subscription,features}:{context:MerchantContext|null;subscription:Subscription|null;features:PlanFeature[]}){const label=context?.plan_code==='community_free'?'Free':context?.plan_code==='pro'?'Pro':'Business+';return <section><h2>Plan & billing</h2><div className="plan-card"><strong>{label}</strong><span>Status: {subscription?.status||'active'} · {subscription?.billing_period||'manual'} billing</span></div><div className="settings-list">{features.filter(f=>f.enabled).map(f=><Card key={f.feature_code} icon={<CreditCard/>} title={f.feature_code.replaceAll('_',' ')} desc="Included"/>)}</div><p className="tool-footnote">Payment-provider checkout is not connected yet. Paid capabilities are still server-gated by plan and subscription state.</p></section>}
function Upgrade({title}:{title:string}){return <div className="empty"><strong>{title}</strong><p>This capability is not included in the current plan.</p></div>}
function Metric({l,v}:{l:string;v:string}){return <div><span>{l}</span><strong>{v}</strong></div>}
function Card({icon,title,desc}:{icon:React.ReactNode;title:string;desc:string}){return <div className="ops-card"><span className="settings-icon">{icon}</span><span className="settings-copy"><strong>{title}</strong><small>{desc}</small></span></div>}
function msg(e:unknown){return e instanceof Error?e.message:String(e||'Something went wrong')}
