import { useEffect, useMemo, useRef, useState } from 'react'
import { ArrowLeft, Search, ShoppingCart } from 'lucide-react'
import { authApi, getMerchantContexts, getPlanLimits, type MerchantContext, type PaymentMethod, type PlanLimits, type ProductRow } from './lib/posApi'
import { findRetailProducts } from './lib/advancedOpsApi'
import { createRetailOrder } from './lib/remainingOpsApi'
import { getPaymentMethods, type PaymentMethodRow } from './lib/opsApi'

const money=(n:number)=>new Intl.NumberFormat('en-PH',{style:'currency',currency:'PHP',maximumFractionDigits:2}).format(Number(n)||0)
export default function RetailWorkspace(){
 const [context,setContext]=useState<MerchantContext|null>(null);const [contexts,setContexts]=useState<MerchantContext[]>([]);const [products,setProducts]=useState<ProductRow[]>([]);const [payments,setPayments]=useState<PaymentMethodRow[]>([]);const [plan,setPlan]=useState<PlanLimits|null>(null)
 const [query,setQuery]=useState('');const [cart,setCart]=useState<Record<string,number>>({});const [prices,setPrices]=useState<Record<string,number>>({});const [discount,setDiscount]=useState('0');const [payment,setPayment]=useState<PaymentMethod|''>('');const [tendered,setTendered]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const input=useRef<HTMLInputElement>(null)
 const canOverride=context?.role==='owner'||context?.role==='manager'
 const load=async(ctx:MerchantContext)=>{if(!ctx.outlet_id)throw new Error('No active outlet.');setContext(ctx);const [p,pm,limits]=await Promise.all([findRetailProducts(ctx.merchant_id,''),getPaymentMethods(ctx.merchant_id,ctx.outlet_id),getPlanLimits(ctx.plan_code)]);setProducts(p);setPayments(pm);setPlan(limits);setPrices(Object.fromEntries(p.map(x=>[x.id,Number(x.price)])));setPayment(pm.find(x=>x.enabled)?.method||'')}
 useEffect(()=>{void(async()=>{try{const s=await authApi.session();if(!s)throw new Error('Sign in from POS first.');const c=await getMerchantContexts();setContexts(c);if(c[0])await load(c[0]);else throw new Error('No merchant account found.')}catch(e){setError(msg(e))}})()},[])
 useEffect(()=>{if(!context)return;const id=setTimeout(()=>{void findRetailProducts(context.merchant_id,query).then(p=>{setProducts(p);setPrices(old=>({...Object.fromEntries(p.map(x=>[x.id,old[x.id]??Number(x.price)])),...old}))}).catch(e=>setError(msg(e)))},120);return()=>clearTimeout(id)},[query,context?.merchant_id])
 const rows=useMemo(()=>products.filter(p=>cart[p.id]),[products,cart]);const subtotal=rows.reduce((s,p)=>s+(cart[p.id]||0)*(prices[p.id]??Number(p.price)),0);const discountValue=Math.min(Math.max(Number(discount)||0,0),subtotal);const total=subtotal-discountValue;const qty=Object.values(cart).reduce((a,b)=>a+b,0);const change=Math.max(0,(Number(tendered)||0)-total)
 const add=(p:ProductRow)=>{if(p.track_inventory&&p.stock_on_hand<=0)return;setCart(c=>({...c,[p.id]:(c[p.id]||0)+1}));setPrices(x=>({...x,[p.id]:x[p.id]??Number(p.price)}));setQuery('');input.current?.focus()}
 const enter=()=>{const q=query.trim().toLowerCase();if(!q)return;const exact=products.find(p=>p.barcode?.toLowerCase()===q||p.sku?.toLowerCase()===q);if(exact)add(exact);else if(products.length===1)add(products[0])}
 const checkout=async()=>{if(!context?.outlet_id||!payment||!qty)return;setBusy(true);setError('');try{await createRetailOrder({merchantId:context.merchant_id,outletId:context.outlet_id,items:rows.map(p=>({product_id:p.id,quantity:cart[p.id],unit_price:prices[p.id]??Number(p.price)})),paymentMethod:payment,discount:discountValue});setCart({});setDiscount('0');setTendered('');const p=await findRetailProducts(context.merchant_id,'');setProducts(p);setPrices(Object.fromEntries(p.map(x=>[x.id,Number(x.price)])));input.current?.focus()}catch(e){setError(msg(e))}finally{setBusy(false)}}
 const sameMerchant=contexts.filter(c=>c.merchant_id===context?.merchant_id)
 return <div className="app-shell"><main className="content retail-workspace"><header className="ops-head"><button className="secondary small" onClick={()=>history.back()}><ArrowLeft/> POS</button><div><p className="eyebrow">Retail mode</p><h1>{context?.merchant_name||'Fast Checkout'}</h1></div></header>{error&&<div className="inline-error">{error}<button onClick={()=>setError('')}>×</button></div>}{sameMerchant.length>1&&<label className="ops-branch-select">Location<select value={context?.outlet_id||''} onChange={e=>{const c=sameMerchant.find(x=>x.outlet_id===e.target.value);if(c)void load(c)}}>{sameMerchant.map(c=><option key={c.outlet_id||''} value={c.outlet_id||''}>{c.outlet_name}</option>)}</select></label>}
 <div className="retail-search"><Search/><input ref={input} autoFocus value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();enter()}}} placeholder="Scan/type barcode, SKU or product name"/></div>
 <div className="retail-layout"><section><div className="product-grid">{products.map(p=><button key={p.id} className="product-card" disabled={!p.active||(p.track_inventory&&p.stock_on_hand<=0)} onClick={()=>add(p)}><span>{p.sku||p.barcode||'Product'}</span><strong>{p.name}</strong><b>{money(p.price)}</b>{p.track_inventory&&<small>{p.stock_on_hand} catalog stock</small>}</button>)}</div></section><aside className="retail-cart"><h2><ShoppingCart/> Cart · {qty}</h2>{rows.length===0?<p className="body-copy">Add a product to start a sale.</p>:rows.map(p=><div className="retail-line" key={p.id}><div><strong>{p.name}</strong>{canOverride?<input aria-label={`Unit price for ${p.name}`} type="number" min="0" step="0.01" value={prices[p.id]??Number(p.price)} onChange={e=>setPrices(x=>({...x,[p.id]:Number(e.target.value)}))}/>:<small>{money(p.price)} each</small>}</div><div><button onClick={()=>setCart(c=>({...c,[p.id]:Math.max(0,(c[p.id]||0)-1)}))}>−</button><b>{cart[p.id]}</b><button onClick={()=>add(p)}>+</button></div></div>)}<div className="retail-total"><span>Subtotal</span><strong>{money(subtotal)}</strong></div>{canOverride&&<label>Discount amount<input type="number" min="0" step="0.01" value={discount} onChange={e=>setDiscount(e.target.value)}/></label>}<div className="retail-total"><span>Total</span><strong>{money(total)}</strong></div><label>Payment<select value={payment} onChange={e=>setPayment(e.target.value as PaymentMethod)}><option value="">Choose</option>{payments.filter(p=>p.enabled).map(p=><option key={p.id} value={p.method}>{p.label}</option>)}</select></label>{payment==='cash'&&<><label>Cash received<input inputMode="decimal" value={tendered} onChange={e=>setTendered(e.target.value)}/></label><div className="retail-change"><span>Change</span><strong>{money(change)}</strong></div></>}<button className="primary" disabled={busy||!qty||!payment||(payment==='cash'&&Number(tendered)<total)} onClick={()=>void checkout()}>{busy?'Saving…':'Complete sale'}</button><small className="tool-footnote">Price overrides and discounts require owner or manager approval. Plan: {plan?.plan_code||context?.plan_code}.</small></aside></div></main></div>
}
function msg(e:unknown){return e instanceof Error?e.message:String(e||'Something went wrong')}
